In [1]:
def get_db():
    from pymongo import MongoClient
    
    try:
        conn = MongoClient('mongodb://192.168.2.20:27017')
        # Connect to DB "mydbname"
        db = conn.prices_db
        return db    
    except pymongo.errors.ConnectionFailure, e:
        print "Could not connect to MongoDB: %s" % e 
        raise e

In [2]:
# Get the connection to our source database
mydb = get_db()

import pandas as pd

# ONS Item No 310218 is Apple Cider, 310421 is red wine, 211709 is semi-skimmed milk
df = pd.DataFrame(list(mydb.combined.find({"ons_item_no": { "$in": [310218, 310421, 211710,211709]}}, \
        {"_id":0,"timestamp":1,"ml_prediction":1,"store":1, "ons_item_no":1,"ons_item_name":1,"std_price":1, "std_unit":1,"product_name":1})))

# Show the first few records in the frame

In [3]:
df1 = df.sort_values("timestamp")

In [4]:
import numpy as np
np.unique(df1["timestamp"])[-20:-1]

array([u'2016-07-07 05:28:40.732563', u'2016-07-07 05:28:40.735025',
       u'2016-07-07 05:28:40.737457', u'2016-07-07 05:28:44.097851',
       u'2016-07-07 05:28:44.100893', u'2016-07-07 05:28:44.103449',
       u'2016-07-07 05:28:44.106068', u'2016-07-07 05:28:44.108683',
       u'2016-07-07 05:28:44.111329', u'2016-07-07 05:28:44.113922',
       u'2016-07-07 05:28:44.116507', u'2016-07-07 05:28:44.118861',
       u'2016-07-07 05:28:44.121588', u'2016-07-07 05:28:44.124100',
       u'2016-07-07 05:28:44.126668', u'2016-07-07 05:28:44.129214',
       u'2016-07-07 05:28:44.131857', u'2016-07-07 05:28:44.134639',
       u'2016-07-07 05:28:44.137389'], dtype=object)

In [5]:
df.tail(20)

,ml_prediction,ons_item_name,ons_item_no,product_name,std_price,std_unit,store,timestamp
769603,1.0,"Shop Milk, whole milk",211709,ESSENTIAL WAITROSE WHOLE MILK 3.6% FAT 1 PINT,0.863,l,WAITROSE,2016-07-04 05:11:53.759732
769604,1.0,"Shop Milk, whole milk",211709,ESSENTIAL WAITROSE WHOLE MILK 3.6% FAT 6 PINTS,0.434,l,WAITROSE,2016-07-04 05:11:53.763273
769605,1.0,"Shop Milk, whole milk",211709,GRAHAMS DAIRY THE ORIGINAL GOLD TOP,,,WAITROSE,2016-07-04 05:11:53.766887
769606,1.0,"Shop Milk, whole milk",211709,CRAVENDALE FRESH FILTERED WHOLE MILK,,,WAITROSE,2016-07-04 05:11:53.770070
769607,1.0,"Shop Milk, whole milk",211709,JERSEY GOLD SMOOTH,1.19,l,WAITROSE,2016-07-04 05:11:53.773268
769608,1.0,"Shop Milk, whole milk",211709,A2 WHOLE FRESH MILK,1.39,l,WAITROSE,2016-07-04 05:11:53.776891
769609,1.0,"Shop Milk, whole milk",211709,CRAVENDALE WHOLE MILK,1.2,l,WAITROSE,2016-07-04 05:11:53.780617
769610,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,ESSENTIAL WAITROSE SEMI-SKIMMED MILK 1.7% FAT ...,0.44,l,WAITROSE,2016-07-04 05:12:01.265107
769611,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,WAITROSE DUCHY ORGANIC SEMI-SKIMMED MILK UN-HO...,0.814,l,WAITROSE,2016-07-04 05:12:01.267934
769612,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,WAITROSE DUCHY ORGANIC SEMI-SKIMMED MILK UN-HO...,0.968,l,WAITROSE,2016-07-04 05:12:01.271560
769613,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,YEO VALLEY ORGANIC FRESH SEMI-SKIMMED MILK,,,WAITROSE,2016-07-04 05:12:01.275189
769614,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,WAITROSE DUCHY ORGANIC SEMI-SKIMMED MILK UN-HO...,1.06,l,WAITROSE,2016-07-04 05:12:01.278412
769615,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,YEO VALLEY ORGANIC SEMI-SKIMMED MILK,0.95,l,WAITROSE,2016-07-04 05:12:01.280910
769616,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,CRAVENDALE SEMI SKIMMED MILK,0.95,l,WAITROSE,2016-07-04 05:12:01.283469
769617,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,ESSENTIAL WAITROSE SEMI-SKIMMED MILK 1.7% FAT ...,0.783,l,WAITROSE,2016-07-04 05:12:01.285996
769618,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,ESSENTIAL WAITROSE SEMI-SKIMMED MILK 1.7% FAT ...,0.863,l,WAITROSE,2016-07-04 05:12:01.288185
769619,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,ESSENTIAL WAITROSE SEMI-SKIMMED MILK 1.7% FAT ...,0.434,l,WAITROSE,2016-07-04 05:12:01.290451
769620,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,CRAVENDALE FRESH FILTERED SEMI-SKIMMED,,,WAITROSE,2016-07-04 05:12:01.292772
769621,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,A2 SEMI SKIMMED FRESH MILK,1.39,l,WAITROSE,2016-07-04 05:12:01.294696
769622,1.0,"Shop Milk,semi-skimmed, per 2 pints/1.136 litre",211710,CRAVENDALE SEMI SKIMMED MILK,1.2,l,WAITROSE,2016-07-04 05:12:01.296976

In [17]:
df['ons_item_name'] = df['ons_item_name'].map(lambda x: x.lower())
df['product_name'] = df['product_name'].map(lambda x: x.lower())

In [19]:
df.tail(3)

,ml_prediction,ons_item_name,ons_item_no,product_name,std_price,std_unit,store,timestamp
561986,1,"red wine, european, bottle",310421,"robinsons double concentrate summer fruits, no...",1.15,l,WAITROSE,2016-01-21 09:30:51.909564
561987,1,"red wine, european, bottle",310421,nescafé azera intenso 100g,24.90,kg,WAITROSE,2016-01-21 09:30:51.997827
561988,0,"red wine, european, bottle",310421,this juicy water lemons & limes 1l 1litre,1.15,l,WAITROSE,2016-01-21 09:30:52.088192